create table eagle_watch (
observation_date date,
eagles_seen integer,
note text
);

/* Character data types */

/* 	char(n) creates a fixed length column that  stores exactly (n) characters per row
	regardless of how many characters you insert,
	if you insert fewer than (n) chars postgres will pad the rest of the column 
	with spaces
*/

/* 	varchar(n) creates a variable length column where the maximum length is determined by (n)
	if you insert fewer than (n) characters postgres will not pad the rest of the column with spaces
*/

/* text is a variable length column of unlimited length */

create table char_data_types (
	char_column char(10),
	varchar_column varchar(10),
	text_column text
);

insert into char_data_types
values
('abc', 'abc', 'abc'),
('defghi', 'defghi', 'defghi');


/* Number data types */

/* Integer data types
	smallint, 2 bytes 
	integer, 4 bytes
	bigint, 8 bytes
	use bigint
*/

/* Auto incrementing integers */

/* serial types 
	smallserial, 2bytes
	serial, 4 bytes
	bigserial, 8bytes
*/

/* Auto incrementing with serial */
create table people (
	id serial,
	person_name varchar(100)
);

/* auto incrementing with identity */
generated always as identity. /* tells the database to always fill the column with an auto incremented value,
a user will not be able to insert a value into this column without manually overriding that setting */

generated by default as identity. /* tells the database to fill the column with an auto incremented value by default
if the user does not supply one, this allows for duplicate values */

/* use the first option */

create table people (
	id integer generated always as identity,
	person_name varchar(100)
);

